# This daily workflow will install jupytext, create README.ipynb from README.md, and push it to the master branch.
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  schedule:
    - cron: '42 5 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Build README.ipynb with jupytext
      run: |
        pip install jupytext --upgrade
        jupytext --to notebook README.md
        git add README.ipynb
        git commit -m"Daily update of README.ipynb"
        git push
