
# PAUSED
# This daily workflow will install jupytext, create README.ipynb from README.md, and push it to the master branch.
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Re-build README.ipynb from README.md

# on:
#   schedule:
#     - cron: '42 3 14 * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jupytext --upgrade
    - name: Unstage README.ipynb
      run: |
        git config user.email "53295216+Grim-bot@users.noreply.github.com"
        git config user.name "Felix Grimberg"
        git rm README.ipynb
        git commit -m"Daily update of README.ipynb, pt1"
    - name: Build README.ipynb with jupytext
      run: |
        jupytext --to notebook README.md
    - name: Commit README.ipynb
      run: |
        git add README.ipynb
        git commit -m"Daily update of README.ipynb, pt2"
        git push
